Vagrant.configure("2") do |config|

        (1..1).each do |i|

            config.vm.define "server#{i}" do |client|
   				#client.vm.provider "virtualbox" do |vm|
				#	vm.memory = 4096
				#end
            	client.vm.box = "bento/centos-7"
            	client.vm.network "private_network", ip: "192.168.50.#{i+1}"
                client.vm.synced_folder '/home/'+ENV['USER']+"/git/packer-autobuild", "/packer-autobuild"
                config.vm.provision "shell", inline: "yum -y install epel-release"
                config.vm.provision "shell", inline: "yum -y install unzip git python34 python34-pip python34-devel libffi-devel libgit2-devel nginx postgresql-server gcc"
                config.vm.provision "shell", inline: "pip3 install -r /packer-autobuild/requirements.txt"
                config.vm.provision "shell", inline: "wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip && unzip packer_1.2.5_linux_amd64.zip && mv packer /usr/bin/packer"
            end
        end

end
